package com.example.UC4_Save.Greeting.in.Repository;
import jakarta.persistence.*;

// Creating the entity class to map the java object to the DB table
@Entity
public class Greeting {

    // @Id and @GeneratedValue generate a unique primary key for each record
    @Id // auto generated by the DB according to the corresponding Value
    @GeneratedValue

    // Encapsulated attributes of the class

    private Long id;
    private String message;

    // Default - Constructor of the class JPA needs
        public Greeting(String message){
            this.message = message;
        }

        // getter and setter methods
    public Long getId(){
            return id;
    }
    public String getMessage(){
            return message;
    }

    public void setMessage(String message){
            this.message = message;
    }

}
